### ISSUE TITLE
bedrooms_config.yaml error

### ISSUE THREAD

**Issue by JackW987** [nv-tlabs/ATISS#13]
data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_autoregressive_wocm"
    dataset_directory: "/media/paschalidoud/goproorgohome/3D_FRONT_processed/bedrooms"
    annotation_file: "../config/bedroom_threed_front_splits.csv"
    augmentations: ["rotations"]
    **filter_fn: "threed_front_bedroom"**
    train_stats: "dataset_stats.txt"
    **filter_fn: "no_filtering"**
    room_layout_size: "64,64"

**Comment by paschalidoud** [comment]
Nice catch! Submitted a commit that fixes it!
