### ISSUE TITLE
The old versiond dataset

### ISSUE THREAD

**Issue by JackW987** [nv-tlabs/ATISS#18]
The number of rooms filted out in the new version dataset is inconsistent with that in the paper, which is much less. Could you release the old version dataset?

**Comment by yhw-yhw** [comment]
Did you solve the problem?

**Comment by paschalidoud** [comment]
Hi all,

Unfortunately we are not allowed to release the old dataset. If you want to filter out the scenes provided in the new release, you can follow the steps described in our supplementary. I am closing the issue for now  but feel free to reach out to me via email or from here if you have any further questions.

Best,
Despoina
