### ISSUE TITLE
Positional Embedding in autoregressive_transformer.py

### ISSUE THREAD

**Issue by coco-archisketch** [nv-tlabs/ATISS#19]
pe_pos have three (x, y, z) in BaseAutoregressiveTransformer class. 
But, in the AutoregressiveTransformer forward function only `pe_pos_x` and `pe_size_x` used. 
Is it right?
```
pos_f_x = self.pe_pos_x(translations[:, :, 0:1])
pos_f_y = self.pe_pos_x(translations[:, :, 1:2])
pos_f_z = self.pe_pos_x(translations[:, :, 2:3])
pos_f = torch.cat([pos_f_x, pos_f_y, pos_f_z], dim=-1)

size_f_x = self.pe_size_x(sizes[:, :, 0:1])
size_f_y = self.pe_size_x(sizes[:, :, 1:2])
size_f_z = self.pe_size_x(sizes[:, :, 2:3])
```

**Comment by wamiq-reyaz** [comment]
Hey @coco-archisketch,

These are fixed functions with no learned parameters, so it doesn't really matter.

**Comment by paschalidoud** [comment]
Hi @coco-archisketch,

Thanks a lot for your comment. As @wamiq-reyaz pointed out this shouldn't really matter, but you are absolutely right and this is indeed a typo. I just committed a fix that solves this.

Best,
Despoina
