### ISSUE TITLE
Question for generate_scenes.py

### ISSUE THREAD

**Issue by Mr-Faceless** [nv-tlabs/ATISS#23]
![image](https://user-images.githubusercontent.com/50651190/206999658-67dfa8a6-41f5-4802-a0b4-d0e486296c3a.png)

![image](https://user-images.githubusercontent.com/50651190/206999771-ee125eb0-5e45-4d79-aac6-dac5518b228d.png)
when I run generate_scenes.py,I alway get the error like the first picture ,it says my opengl version is 300. but my opengl version is 4.6.0.
Could you please tell me how to fix  this?
Thanys a lot!

**Comment by shanqiiu** [comment]
Hello, is this problem solved?
