### ISSUE TITLE
problem with the /tmp/threed_front.pkl

### ISSUE THREAD

**Issue by hyuk199** [nv-tlabs/ATISS#27]
I've tried to run the preprocess_data.py script. I met the error `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/threed_front.pkl'.`
This is how I ran the preprocess_data.py script:

> Loading dataset  6812 /  6813
> Traceback (most recent call last):
>   File "pickle_threed_future_dataset.py", line 128, in <module>
>     main(sys.argv[1:])
>   File "pickle_threed_future_dataset.py", line 102, in main
>     scenes_dataset = ThreedFront.from_dataset_directory(
>   File "C:\Users\user\Documents\Workspace\ATISS\scene_synthesis\datasets\threed_front.py", line 169, in from_dataset_directory
>     scenes = parse_threed_front_scenes(
>   File "C:\Users\user\Documents\Workspace\ATISS\scene_synthesis\datasets\utils.py", line 129, in parse_threed_front_scenes
>     pickle.dump(scenes, open("tmp\threed_front.pkl", "wb"))
> OSError: [Errno 22] Invalid argument: 'tmp\threed_front.pkl'
> 

Please help me.

**Comment by kkkkkkkkkkkkkkkin** [comment]
Have you tried changing the code to 
`pickle.dump(scenes, open("./tmp/threed_front.pkl", "wb"))`

or just hardcode the path in with
`pickle.dump(scenes, open(r"C:\yourpath", "wb"))`

It's been a while since I fixed the problem, so I am not sure how I fixed the problem back then.

I hope this helps.

**Comment by hyuk199** [comment]
> Have you tried changing the code to `pickle.dump(scenes, open("./tmp/threed_front.pkl", "wb"))`
> 
> or just hardcode the path in with `pickle.dump(scenes, open(r"C:\yourpath", "wb"))`
> 
> It's been a while since I fixed the problem, so I am not sure how I fixed the problem back then.
> 
> I hope this helps.

It didn't work for `"./tmp/threed_front.pkl"`, so I wrote issue
and it worked on hardcode! `pickle.dump(scenes, open(r"C:\yourpath", "wb"))`
Thank you so much!

**Comment by k-bobin** [comment]
hI i run into the exact same problem.
could you clarify what "yourpath" is?
As like you,  "./tmp/threed_front.pkl" does not work. so  I'd try the other way to resolve the issue.
When you say pickle.dump(scenes, open(r"C:\yourpath", "wb")) does your path means path to threed_front.pkl?l if it does, does it even have path? I thought it is supposed to create when code executed perfectly
