### ISSUE TITLE
floor_plan_texture_images issue

### ISSUE THREAD

**Issue by hayaokar** [nv-tlabs/ATISS#30]
hello, I'm wondering if this folder exists already or if I have to create it and gather some textures, cause I can't find it anywhere and it's causing errors. Help me, please.

**Comment by kkkkkkkkkkkkkkkin** [comment]
Hi, the textures should be inside the ./demo/floor_plan_texture_images folder.

**Comment by paschalidoud** [comment]
Hi @hayaokar,

As @kkkkkkkkkkkkkkkin said the texture images for the floors are within the demo folder in the floor_plan_texture_images folder.

Best,
Despi
