### ISSUE TITLE
errow when executing preprocess_data.py

### ISSUE THREAD

**Issue by Caesarr007** [nv-tlabs/ATISS#41]
as follows:

Applying threed_front_bedroom filtering
Loading dataset  6812 /  6813
Loading dataset with 3879 rooms
Saving training statistics for dataset with bounds: {'translations': (array([-2.7625005,  0.045    , -2.75275  ]), array([2.77844175, 3.6248396 , 2.81854277])), 'sizes': (array([0.03998288, 0.02000002, 0.012772  ]), array([2.8682  , 1.770065, 1.698315])), 'angles': (array([-3.14159265]), array([3.14159265]))} to path_to_output_dir/dataset_stats.txt
Applying threed_front_bedroom filtering
Loading dataset  6812 /  6813
{'translations': (array([-2.7625005,  0.045    , -2.75275  ]), array([2.77844175, 3.6248396 , 2.81854277])), 'sizes': (array([0.0350001 , 0.02000002, 0.012772  ]), array([2.8682  , 1.770065, 1.698315])), 'angles': (array([-3.14159265]), array([3.14159265]))}
Loading dataset with 4041 rooms
1it [00:00,  5.29it/s]
Traceback (most recent call last):
  File "preprocess_data.py", line 271, in <module>
    main(sys.argv[1:])
  File "preprocess_data.py", line 258, in main
    renderables = get_textured_objects_in_scene(
  File "/userhome3/wangzheng/ATISS-from-paper/ATISS-master/scripts/utils.py", line 138, in get_textured_objects_in_scene
    raw_mesh = TexturedMesh.from_file(model_path)
  File "/userhome3/wangzheng/anaconda3/envs/atiss-from-paper/lib/python3.8/site-packages/simple_3dviz/renderables/textured_mesh.py", line 300, in from_file
    mtl = read_material_file(mesh.material_file)
  File "/userhome3/wangzheng/anaconda3/envs/atiss-from-paper/lib/python3.8/site-packages/simple_3dviz/io/__init__.py", line 27, in read_material_file
    return {
  File "/userhome3/wangzheng/anaconda3/envs/atiss-from-paper/lib/python3.8/site-packages/simple_3dviz/io/material.py", line 25, in __init__
    self.read(filename)
  File "/userhome3/wangzheng/anaconda3/envs/atiss-from-paper/lib/python3.8/site-packages/simple_3dviz/io/material.py", line 113, in read
    self._Ns = float([
IndexError: list index out of range

i presonally think this error happens when rendering objects in the room? but i have no idea how to fix.
i can get some results as the paste
![Snipaste_2023-12-04_20-08-22](https://github.com/nv-tlabs/ATISS/assets/94221299/80555ac9-5b84-4dc3-a738-53f642accbed)

**Comment by skf-1999** [comment]
hi I solve this problem.
lib\site-packages\simple_3dviz\io\material.py
            '''
            self._Ns = float([
                float(l.strip().split()[1:][0])
                for l in lines if l.strip().startswith("Ns")
            ][0])
            '''
            self._Ns = 400

**Comment by SunYanbo2002** [comment]
> hi I solve this problem. lib\site-packages\simple_3dviz\io\material.py ''' self._Ns = float([ float(l.strip().split()[1:][0]) for l in lines if l.strip().startswith("Ns") ][0]) ''' self._Ns = 400

After the modification, the following problems appear. Have you encountered this problem? thank you
![image](https://github.com/user-attachments/assets/ff158e53-140f-469b-b5d3-f327e667c9b7)

**Comment by ky-zhou** [comment]
> hi I solve this problem. lib\site-packages\simple_3dviz\io\material.py ''' self._Ns = float([ float(l.strip().split()[1:][0]) for l in lines if l.strip().startswith("Ns") ][0]) ''' self._Ns = 400

Hi, how did you solve it? What you posted was the same as the original code.
