### ISSUE TITLE
Do a core-ML version

### ISSUE THREAD

**Issue by julienbelangerunity** [nv-tlabs/ATISS#8]
I'd love to be able to try the algorithm with no-rendering and all the madness, I'd love to see a minimal version with only the ML core like Dataset in and torch tensor out.

**Comment by paschalidoud** [comment]
Hi @julienbelangerunity,

Thanks for your feedback. The "ML core" of our code can be found within the networks folder of our repository. This part of the code is completely independent of rendering etc. 

Best,
Despoina
